table=read.table("household_power_consumption.txt",sep = ";",stringsAsFactors = FALSE,header = TRUE)
table$Date = as.Date(table$Date,"%d/%m/%Y")
table_subset = subset(table,Date == "2007-02-01" | Date == "2007-02-02")
table_subset$Time=strptime(table_subset$Time,format = "%H:%M:%S")
table_subset$Time=format(as.POSIXct(table_subset$Time),"%H:%M:%S")
str(table_subset)
table_subset$Global_active_power=as.numeric(table_subset$Global_active_power)
hist(table_subset$Global_active_power,col="red",xlab = "Global Active Power(kilowatts)",main = c("Global Active Power"))
png("plot1.png",width=480,height=480)
hist(table_subset$Global_active_power,col="red",xlab = "Global Active Power(kilowatts)",main = c("Global Active Power"))
dev.off()
